version: "2"
checks:
  argument-count:
    config:
      threshold: 6
  method-lines:
    config:
      threshold: 30
  similar-code:
    enabled: false
plugins:
  sonar-java:
    enabled: true
    config:
      sonar.java.source: 8
  checkstyle:
    enabled: true
    config:
      file: config/checkstyle/checkstyle.xml
  editorconfig:
    enabled: true
    channel: beta
  fixme:
    enabled: false
