app.path.prefix: ${APP_PATH_PREFIX:}

bams.api.springfox:
  # Path the service is hosted at (e.g., the Kong path prefix)
  basePath: ${PATH_PREFIX:/}
  title: "Gatekeeper"

logging.level:
  org.springframework.security: INFO

spring.zipkin.service.name: ${systemEnvironment['SERVICE_NAME']:gatekeeper}

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
